name: kernel-snapium-b4s4
version: "4.9"
summary: kernel snap for the Google Pixel 3a
description: kernel snap for the Google Pixel 3a
grade: stable
confinement: strict
type: kernel
build-base: core22
architectures:
  - build-on: arm64
parts:
 kernel:
    plugin: kernel
    source: .
    kernel-kdefconfig: [ lineageos_bonito_defconfig ]
    kernel-image-target: Image
    kernel-compiler: clang
    kernel-with-firmware: false
    kernel-initrd-compression: lz4
    kernel-compiler-parameters:
      - W=1
      - CROSS_COMPILE_ARM32=arm-linux-gnueabihf-
    build-packages:
      - clang
      - binutils-aarch64-linux-gnu
      - libc6-arm64-cross
      - libc6-dev-arm64-cross
      - crossbuild-essential-arm64
      - crossbuild-essential-armhf
      - python2
    override-pull: |
      craftctl default
    override-build: |
      ln -sf /usr/bin/python2.7 /usr/bin/python
      mkdir -p $CRAFT_PART_INSTALL/lib/firmware
      echo "# Empty on purpose" > $CRAFT_PART_INSTALL/lib/firmware/README.md
      craftctl default
